version: '3'
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000"
    volumes:
      - ./project:/app
    command: npm run start
    labels:
      - traefik.enable=true
      - traefik.http.routers.cybersecurity-wars.rule=PathPrefix(`/`)
      - traefik.http.routers.cybersecurity-wars.service=cybersecurity-wars
      - traefik.http.routers.cybersecurity-wars.entrypoints=dev
      - traefik.http.services.cybersecurity-wars.loadbalancer.server.port=8000
    networks:
      - dev_network
networks:
  dev_network:
    external: true
